// Mock data for products
export const products = [
  {
    id: 1,
    name: "Good Day",
    description: "Rich butter cookies with a perfect crunch",
    price: 25.0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Cookies",
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 2,
    name: "Marie Gold",
    description: "Light and crispy tea-time biscuits",
    price: 20.0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Biscuits",
    isNew: false,
    isBestSeller: true,
  },
  {
    id: 3,
    name: "Bourbon",
    description: "Chocolate sandwich cookies with creamy filling",
    price: 30.0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Cookies",
    isNew: false,
    isBestSeller: false,
  },
  {
    id: 4,
    name: "Little Hearts",
    description: "Sweet and crispy heart-shaped delights",
    price: 15.0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Biscuits",
    isNew: false,
    isBestSeller: false,
  },
  {
    id: 5,
    name: "Milk Bikis",
    description: "Nutritious milk biscuits for growing children",
    price: 22.0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Biscuits",
    isNew: false,
    isBestSeller: false,
  },
  {
    id: 6,
    name: "Nutrichoice",
    description: "Healthy digestive biscuits with high fiber",
    price: 35.0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Biscuits",
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 7,
    name: "Pure Magic",
    description: "Chocolate-filled indulgent cookies",
    price: 40.0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Cookies",
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 8,
    name: "50-50",
    description: "Perfect balance of sweet and salty biscuits",
    price: 18.0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Biscuits",
    isNew: false,
    isBestSeller: false,
  },
  {
    id: 9,
    name: "Treat Croissant",
    description: "Soft croissants with chocolate filling",
    price: 45.0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Cakes",
    isNew: true,
    isBestSeller: false,
  },
  {
    id: 10,
    name: "Treat Burst",
    description: "Soft cakes with fruity fillings",
    price: 42.0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Cakes",
    isNew: false,
    isBestSeller: false,
  },
  {
    id: 11,
    name: "Milk Bread",
    description: "Soft and nutritious milk bread",
    price: 30.0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Bread",
    isNew: false,
    isBestSeller: false,
  },
  {
    id: 12,
    name: "Brown Bread",
    description: "Healthy whole wheat brown bread",
    price: 35.0,
    image: "/placeholder.svg?height=400&width=400",
    category: "Bread",
    isNew: false,
    isBestSeller: false,
  },
]

// Mock data for recipes
export const recipes = [
  {
    id: 1,
    title: "Bourbon Chocolate Trifle",
    description: "A decadent dessert made with layers of Bourbon biscuits, chocolate pudding, and whipped cream.",
    image: "/placeholder.svg?height=600&width=800",
    time: "30 min",
    servings: 4,
    difficulty: "Easy",
    category: "Desserts",
    ingredients: [
      "12 Bourbon biscuits",
      "2 cups chocolate pudding",
      "1 cup whipped cream",
      "1/4 cup chocolate shavings",
      "2 tbsp sugar",
    ],
    instructions: [
      "Crush the Bourbon biscuits into coarse crumbs.",
      "In serving glasses, layer the biscuit crumbs, chocolate pudding, and whipped cream.",
      "Repeat the layers, ending with whipped cream on top.",
      "Garnish with chocolate shavings and refrigerate for at least 2 hours before serving.",
    ],
  },
  {
    id: 2,
    title: "Marie Gold Cheesecake",
    description: "A no-bake cheesecake with a Marie Gold biscuit base and a creamy vanilla topping.",
    image: "/placeholder.svg?height=600&width=800",
    time: "45 min",
    servings: 6,
    difficulty: "Medium",
    category: "Desserts",
    ingredients: [
      "20 Marie Gold biscuits",
      "1/2 cup melted butter",
      "2 cups cream cheese",
      "1 cup whipping cream",
      "1/2 cup sugar",
      "1 tsp vanilla extract",
      "2 tbsp gelatin",
    ],
    instructions: [
      "Crush the Marie Gold biscuits and mix with melted butter.",
      "Press the mixture into the base of a springform pan and refrigerate.",
      "Beat cream cheese, sugar, and vanilla until smooth.",
      "Fold in whipped cream and dissolved gelatin.",
      "Pour over the biscuit base and refrigerate for at least 4 hours.",
    ],
  },
  {
    id: 3,
    title: "Good Day Cookie Ice Cream",
    description: "Homemade vanilla ice cream with chunks of Good Day cookies for added crunch and flavor.",
    image: "/placeholder.svg?height=600&width=800",
    time: "60 min",
    servings: 8,
    difficulty: "Medium",
    category: "Desserts",
    ingredients: [
      "2 cups heavy cream",
      "1 cup milk",
      "3/4 cup sugar",
      "1 tbsp vanilla extract",
      "8 Good Day cookies, chopped",
    ],
    instructions: [
      "Mix heavy cream, milk, sugar, and vanilla in a bowl.",
      "Pour the mixture into an ice cream maker and churn according to manufacturer's instructions.",
      "When the ice cream is almost set, add the chopped Good Day cookies.",
      "Transfer to a container and freeze for at least 2 hours before serving.",
    ],
  },
  {
    id: 4,
    title: "Little Hearts Strawberry Parfait",
    description: "A delightful layered dessert with Little Hearts biscuits, strawberries, and cream.",
    image: "/placeholder.svg?height=600&width=800",
    time: "20 min",
    servings: 4,
    difficulty: "Easy",
    category: "Desserts",
    ingredients: [
      "2 cups Little Hearts biscuits",
      "2 cups fresh strawberries, sliced",
      "1 cup whipped cream",
      "2 tbsp honey",
      "1/4 cup strawberry sauce",
    ],
    instructions: [
      "Layer Little Hearts biscuits at the bottom of serving glasses.",
      "Add a layer of sliced strawberries and drizzle with honey.",
      "Top with whipped cream and repeat the layers.",
      "Finish with a drizzle of strawberry sauce and a few Little Hearts on top.",
      "Serve immediately or refrigerate for up to 1 hour.",
    ],
  },
  {
    id: 5,
    title: "Nutrichoice Granola Bars",
    description: "Healthy homemade granola bars using Nutrichoice biscuits, nuts, and dried fruits.",
    image: "/placeholder.svg?height=600&width=800",
    time: "40 min",
    servings: 12,
    difficulty: "Medium",
    category: "Snacks",
    ingredients: [
      "2 cups crushed Nutrichoice biscuits",
      "1 cup mixed nuts (almonds, walnuts, cashews)",
      "1/2 cup dried fruits (raisins, cranberries)",
      "1/3 cup honey",
      "1/4 cup peanut butter",
      "2 tbsp flaxseeds",
    ],
    instructions: [
      "Mix crushed Nutrichoice biscuits, nuts, dried fruits, and flaxseeds in a bowl.",
      "Heat honey and peanut butter until well combined.",
      "Pour the honey mixture over the dry ingredients and mix well.",
      "Press the mixture into a lined baking tray and refrigerate for at least 2 hours.",
      "Cut into bars and store in an airtight container.",
    ],
  },
  {
    id: 6,
    title: "Milk Bikis Breakfast Pudding",
    description: "A nutritious breakfast pudding made with Milk Bikis, milk, and fruits.",
    image: "/placeholder.svg?height=600&width=800",
    time: "15 min",
    servings: 2,
    difficulty: "Easy",
    category: "Breakfast",
    ingredients: [
      "10 Milk Bikis biscuits",
      "1 cup milk",
      "1 banana, sliced",
      "1/4 cup mixed berries",
      "1 tbsp honey",
      "1 tsp chia seeds",
    ],
    instructions: [
      "Crush the Milk Bikis biscuits into a coarse powder.",
      "Mix with milk and let it sit for 5 minutes to soften.",
      "Top with sliced banana, mixed berries, and chia seeds.",
      "Drizzle with honey and serve immediately.",
    ],
  },
  {
    id: 7,
    title: "50-50 Savory Tart Crust",
    description: "A unique savory tart crust made with 50-50 biscuits, perfect for quiches and savory pies.",
    image: "/placeholder.svg?height=600&width=800",
    time: "35 min",
    servings: 6,
    difficulty: "Medium",
    category: "Snacks",
    ingredients: [
      "20 50-50 biscuits",
      "1/2 cup melted butter",
      "1 tsp dried herbs (thyme, rosemary)",
      "1/4 tsp salt",
      "1/4 tsp black pepper",
    ],
    instructions: [
      "Preheat oven to 350°F (175°C).",
      "Crush the 50-50 biscuits into fine crumbs.",
      "Mix with melted butter, herbs, salt, and pepper.",
      "Press the mixture into a tart pan and bake for 10-12 minutes until golden.",
      "Let it cool before filling with your favorite savory filling.",
    ],
  },
  {
    id: 8,
    title: "Pure Magic Chocolate Milkshake",
    description: "An indulgent chocolate milkshake made with Pure Magic cookies for extra chocolate goodness.",
    image: "/placeholder.svg?height=600&width=800",
    time: "10 min",
    servings: 2,
    difficulty: "Easy",
    category: "Drinks",
    ingredients: [
      "6 Pure Magic cookies",
      "2 cups milk",
      "2 scoops vanilla ice cream",
      "2 tbsp chocolate sauce",
      "Whipped cream for topping",
      "Chocolate sprinkles",
    ],
    instructions: [
      "Blend 4 Pure Magic cookies with milk, ice cream, and chocolate sauce until smooth.",
      "Pour into glasses and top with whipped cream.",
      "Crush the remaining cookies and sprinkle on top along with chocolate sprinkles.",
      "Serve immediately with a straw and spoon.",
    ],
  },
]
